'use client'

import { useEffect } from 'react'

import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import { createHelia } from 'helia'
import { json as heliaJson } from '@helia/json'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  useEffect(() => {
    (async () => {
      const h = await createHelia()
      const j = heliaJson(h)
      const r = await j.get("QmUr1PJ3XFKDVYrgjuMUMUXYCFXHXrQfzhzSLHZiwTTi8H")
      console.log("r:", r)
    })()
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}></main>
    </>
  )
}
